### ISSUE TITLE
Write SQL script 

### ISSUE THREAD

**Issue by RunpengNie** [RunpengNie/underdog-s-struggling#11]
After a short discussion with a senior SDE from Microsoft, I believe this project is more suitable for using RDBMS (like MySQL) to store document content than Dynamo DB. Now, we need to write the script for building the database according to the design documents.

**Comment by Junzhou-712** [comment]
Could you expand that?

**Comment by TonyLiu836** [comment]
Had some basic questions about the types of the columns.

```
Users: Store user information
--     UserID (PK)   
--     UserName  ***
--     Password
--     Role (FK, to Roles.RoleID)  ***
--     Email (Unique)
--     RegistrationDate 
```
UserName should be UNIQUE  right? And should Role be an ENUM or some other datatype? Design doc doesn't really specify how Role is envisioned.


```
Entries: Store knowledge entries
--     EntryID (PK)
--     Title (Unique)
--     Topic/SubTitle
--     Order   ***
--     Content
--     AuthorID (FK, to Users.UserID)
--     CreatedDate
--     LastModifyDate
```
Not sure what Order is supposed to mean. What exactly is this column storing?

**Comment by RunpengNie** [comment]
> Had some basic questions about the types of the columns.
> 
> ```
> Users: Store user information
> --     UserID (PK)   
> --     UserName  ***
> --     Password
> --     Role (FK, to Roles.RoleID)  ***
> --     Email (Unique)
> --     RegistrationDate 
> ```
> 
> UserName should be UNIQUE right? And should Role be an ENUM or some other datatype? Design doc doesn't really specify how Role is envisioned.
> 
> ```
> Entries: Store knowledge entries
> --     EntryID (PK)
> --     Title (Unique)
> --     Topic/SubTitle
> --     Order   ***
> --     Content
> --     AuthorID (FK, to Users.UserID)
> --     CreatedDate
> --     LastModifyDate
> ```
> 
> Not sure what Order is supposed to mean. What exactly is this column storing?

As for the username, I'm not sure if we should make it unique, a lot of apps don't allow duplicate usernames, but there are a lot of apps that do, I think this needs to be discussed. @Junzhou-712 @VincentXiao997 What are your thoughts?

`Role` should be `int` type. `Role` defines the permissions of different users. In the preliminary plan, we have three roles, administrator(developers, which is us), VIP user(paid user) and ordinary user. 

`Order` defines the position of each entry on the page, which can also be understood as the index of each entry on the page. The smaller the order, the higher the entry is located.

**Comment by RunpengNie** [comment]
Since we use JPA in this project, we do not need to manually write and run the SQL script. But I still store the SQL script in the repo to let new comers to learn some database design techniques if they need.
