### ISSUE TITLE
Bugfix: we need `Language` for every entry

### ISSUE THREAD

**Issue by Junzhou-712** [RunpengNie/underdog-s-struggling#26]
After a thorough code review, entity `entry` lacks of attribute language

**Comment by RunpengNie** [comment]
As we discussed, this will include entity design change and more tables in databases: 
Add Language Entity/Table.
Add Entry-Language joiner table. 
Do not forget to update design document.

**Comment by RunpengNie** [comment]
Joe also found a bug in `Entry` class, he will solve these in one PR.
